import { randomBytes } from 'node:crypto';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { toB64url } from '@attendly/protocol';
import { loadConfig } from '../src/config';
import { createServerSigner } from '../src/lib/keys';
import { seedDemo } from '../src/seed';
import { DEV_PAGE } from '../src/routes/dev';
import { createTestApp, type TestCtx } from './harness';

const TOKEN = 'Ab+cd/EF==gh' + 'x'.repeat(24); // contains characters that URLs mangle

let ctx: TestCtx;
beforeAll(async () => {
  ctx = await createTestApp({ DEV_TOOLS_TOKEN: TOKEN });
});
afterAll(async () => ctx?.close());

describe('config', () => {
  it('accepts standard base64 keys with padding (as generated by hosting dashboards)', () => {
    const raw = randomBytes(32);
    const base = { NODE_ENV: 'test', DATABASE_URL: 'postgres://x', TOKEN_PEPPER: toB64url(new Uint8Array(randomBytes(32))) };
    const std = loadConfig({ ...base, SERVER_SIGNING_KEY: raw.toString('base64') });
    const url = loadConfig({ ...base, SERVER_SIGNING_KEY: raw.toString('base64url') });
    expect(Buffer.from(std.serverSigningSeed).equals(raw)).toBe(true);
    expect(createServerSigner(std.serverSigningSeed).kid).toBe(createServerSigner(url.serverSigningSeed).kid);
    expect(() => loadConfig({ ...base, SERVER_SIGNING_KEY: 'short' })).toThrow(/SERVER_SIGNING_KEY/);
    expect(() => loadConfig({ ...base, SERVER_SIGNING_KEY: raw.toString('base64'), NODE_ENV: 'production' })).toThrow(/OTP_DELIVERY/);
  });

  it('rejects the same key bytes reused as pepper, even in a different base64 spelling', () => {
    const raw = randomBytes(32);
    const env = { NODE_ENV: 'test', DATABASE_URL: 'postgres://x', SERVER_SIGNING_KEY: raw.toString('base64'), TOKEN_PEPPER: raw.toString('base64url') };
    expect(() => loadConfig(env)).toThrow(/TOKEN_PEPPER/);
  });

  it('requires a dev token with real entropy after normalisation', () => {
    const env = { NODE_ENV: 'test', DATABASE_URL: 'postgres://x', SERVER_SIGNING_KEY: toB64url(new Uint8Array(randomBytes(32))), TOKEN_PEPPER: toB64url(new Uint8Array(randomBytes(32))) };
    expect(() => loadConfig({ ...env, DEV_TOOLS_TOKEN: '------------------------a' })).toThrow(/DEV_TOOLS_TOKEN/);
    expect(loadConfig({ ...env, DEV_TOOLS_TOKEN: 'A'.repeat(24) }).devToolsToken).toBe('A'.repeat(24));
  });
});

describe('dev console', () => {
  it('page script is valid JavaScript (a syntax error silently disables every button)', () => {
    const scripts = [...DEV_PAGE.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((m) => m[1]!);
    expect(scripts.length).toBeGreaterThan(0);
    for (const src of scripts) expect(() => new Function(src)).not.toThrow();
  });

  it('is hidden without the token and tolerates URL-mangled tokens', async () => {
    expect((await ctx.app.inject({ method: 'GET', url: '/dev' })).statusCode).toBe(404);
    expect((await ctx.app.inject({ method: 'GET', url: '/dev?token=wrong' })).statusCode).toBe(404);
    // "+" arrives as a space and "/" / "=" may be percent-encoded when pasted into a browser.
    const mangled = encodeURIComponent(TOKEN).replace(/%2B/g, '+');
    const r = await ctx.app.inject({ method: 'GET', url: `/dev?token=${mangled}` });
    expect(r.statusCode).toBe(200);
    expect(r.headers['content-type']).toMatch(/text\/html/);
  });

  it('shows recent sign-in codes (console delivery only)', async () => {
    const res = await ctx.app.inject({ method: 'GET', url: '/dev/api/codes', headers: { 'x-dev-token': TOKEN } });
    expect(res.statusCode).toBe(200);
    expect(Array.isArray(res.json())).toBe(true);
  });
});

describe('demo seed', () => {
  it('seeds once, is idempotent, and keeps the audit chain valid', async () => {
    const quiet = { log: () => {} };
    expect(await seedDemo(ctx.db, ctx.deps.config, quiet)).toBe(true);
    expect(await seedDemo(ctx.db, ctx.deps.config, quiet)).toBe(false);
    // The default logger (used by `npm run seed`) must work too.
    const logs: unknown[] = [];
    const orig = console.log;
    console.log = (...a: unknown[]) => void logs.push(a);
    try {
      expect(await seedDemo(ctx.db, ctx.deps.config)).toBe(false);
    } finally {
      console.log = orig;
    }
    expect(String(logs[0])).toMatch(/already exists/);
    const { rows } = await ctx.db.query(`select count(*)::int as n from users u join tenants t on t.id = u.tenant_id where t.slug = 'demo' and u.role = 'student'`);
    expect(rows[0].n).toBe(11);
    const aarav = await ctx.db.query(`select 1 from users where email = 'aarav@demo.attendly.app'`);
    expect(aarav.rowCount).toBe(1);
  });
});
